"""
Django settings for myproject.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
import dj_database_url
from pathlib import Path
from datetime import timedelta

# ======================================================================
# 🌍 CẤU HÌNH CHUNG
# ======================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Giữ nguyên key như yêu cầu
SECRET_KEY = "django-insecure-($p^!x%h3bl5e$!0yma(q-@z9c1ke+1^k&0q@r6%vn4-oe3v4d"

# Giữ nguyên Debug = True
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://moneytrackbot.onrender.com']


# ======================================================================
# ⚙️ ỨNG DỤNG
# ======================================================================

INSTALLED_APPS = [
    # Django mặc định
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Thư viện bên thứ ba
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",

    # Ứng dụng của bạn
    "api.apps.ApiConfig",
]


# ======================================================================
# 🧱 MIDDLEWARE
# ======================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # Nên dùng cái này trên Render cho nhanh
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ======================================================================
# 🚀 URL & WSGI
# ======================================================================

ROOT_URLCONF = "myproject.urls"
WSGI_APPLICATION = "myproject.wsgi.application"


# ======================================================================
# 🎨 TEMPLATE
# ======================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ======================================================================
# 🗄️ CƠ SỞ DỮ LIỆU (Đã cập nhật logic PostgreSQL)
# ======================================================================

# Mặc định là SQLite (cho máy tính)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 🔥 Nếu phát hiện đang chạy trên Render (có DATABASE_URL) -> Tự động chuyển sang PostgreSQL
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES["default"] = dj_database_url.parse(
        database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )


# ======================================================================
# 🔒 KIỂM TRA MẬT KHẨU
# ======================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ======================================================================
# 🕐 NGÔN NGỮ & MÚI GIỜ
# ======================================================================

LANGUAGE_CODE = "vi"
TIME_ZONE = "Asia/Ho_Chi_Minh"
USE_I18N = True
USE_TZ = True


# ======================================================================
# 📦 FILE TĨNH
# ======================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Sử dụng WhiteNoise (nếu bạn đã cài trong requirements.txt)
# Nếu chưa cài whitenoise thì dùng dòng dưới: "django.contrib.staticfiles.storage.StaticFilesStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ======================================================================
# 🔑 KHÓA CHÍNH MẶC ĐỊNH
# ======================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======================================================================
# 🔧 DJANGO REST FRAMEWORK
# ======================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}


# ======================================================================
# 🔐 JSON WEB TOKEN (JWT)
# ======================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ======================================================================
# 🤖 GEMINI API KEY (Giữ nguyên)
# ======================================================================

GEMINI_API_KEY = "AIzaSyBnbrgg4z6gUH6-ALdYivejIF_GHI6Ksqg"