"""
Django settings for myproject.

Generated by 'django-admin startproject' using Django 5.2.7.

Documentation:
    https://docs.djangoproject.com/en/stable/topics/settings/
"""

from pathlib import Path
from datetime import timedelta

# ======================================================================
# 🌍 CẤU HÌNH CHUNG
# ======================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-($p^!x%h3bl5e$!0yma(q-@z9c1ke+1^k&0q@r6%vn4-oe3v4d"

DEBUG = True

ALLOWED_HOSTS = [
    "10.0.2.2",     # Android Emulator
    "127.0.0.1",    # Localhost
    "localhost",
]


# ======================================================================
# ⚙️ ỨNG DỤNG
# ======================================================================

INSTALLED_APPS = [
    # Django mặc định
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Thư viện bên thứ ba
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",

    # Ứng dụng của bạn
    "api.apps.ApiConfig",
]


# ======================================================================
# 🧱 MIDDLEWARE
# ======================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ======================================================================
# 🚀 URL & WSGI
# ======================================================================

ROOT_URLCONF = "myproject.urls"
WSGI_APPLICATION = "myproject.wsgi.application"


# ======================================================================
# 🎨 TEMPLATE
# ======================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ======================================================================
# 🗄️ CƠ SỞ DỮ LIỆU
# ======================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ======================================================================
# 🔒 KIỂM TRA MẬT KHẨU
# ======================================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ======================================================================
# 🕐 NGÔN NGỮ & MÚI GIỜ
# ======================================================================

LANGUAGE_CODE = "vi"
TIME_ZONE = "Asia/Ho_Chi_Minh"
USE_I18N = True
USE_TZ = True


# ======================================================================
# 📦 FILE TĨNH
# ======================================================================

STATIC_URL = "static/"


# ======================================================================
# 🔑 KHÓA CHÍNH MẶC ĐỊNH
# ======================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======================================================================
# 🔧 DJANGO REST FRAMEWORK
# ======================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}


# ======================================================================
# 🔐 JSON WEB TOKEN (JWT)
# ======================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),   # Token sống 1 ngày
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # Refresh token sống 7 ngày
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ======================================================================
# 🤖 GEMINI API KEY (TÙY CHỌN)
# ======================================================================

GEMINI_API_KEY = "AIzaSyBnbrgg4z6gUH6-ALdYivejIF_GHI6Ksqg"
